/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerateJobIdRouteImport } from './routes/generate.$jobId'
import { Route as EditorProjectIdRouteImport } from './routes/editor.$projectId'
import { Route as ApiRuntimeRouteImport } from './routes/api.runtime'
import { Route as ApiImageRouteImport } from './routes/api.image'
import { Route as ApiAudioRouteImport } from './routes/api.audio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateJobIdRoute = GenerateJobIdRouteImport.update({
  id: '/generate/$jobId',
  path: '/generate/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeRoute = ApiRuntimeRouteImport.update({
  id: '/api/runtime',
  path: '/api/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/image': typeof ApiImageRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/generate/$jobId': typeof GenerateJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/image': typeof ApiImageRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/generate/$jobId': typeof GenerateJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/audio': typeof ApiAudioRoute
  '/api/image': typeof ApiImageRoute
  '/api/runtime': typeof ApiRuntimeRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/generate/$jobId': typeof GenerateJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/audio'
    | '/api/image'
    | '/api/runtime'
    | '/editor/$projectId'
    | '/generate/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/audio'
    | '/api/image'
    | '/api/runtime'
    | '/editor/$projectId'
    | '/generate/$jobId'
  id:
    | '__root__'
    | '/'
    | '/api/audio'
    | '/api/image'
    | '/api/runtime'
    | '/editor/$projectId'
    | '/generate/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAudioRoute: typeof ApiAudioRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiRuntimeRoute: typeof ApiRuntimeRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
  GenerateJobIdRoute: typeof GenerateJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/$jobId': {
      id: '/generate/$jobId'
      path: '/generate/$jobId'
      fullPath: '/generate/$jobId'
      preLoaderRoute: typeof GenerateJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId': {
      id: '/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime': {
      id: '/api/runtime'
      path: '/api/runtime'
      fullPath: '/api/runtime'
      preLoaderRoute: typeof ApiRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAudioRoute: ApiAudioRoute,
  ApiImageRoute: ApiImageRoute,
  ApiRuntimeRoute: ApiRuntimeRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
  GenerateJobIdRoute: GenerateJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
